import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import UserSearch from '@/containers/UserSearch';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
    return (
        <>
            <Head>
                <title>Search users</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex justify-center min-h-screen">
                <div className="my-36 md:w-96">
                    <h1 className="text-3xl font-bold">Search users</h1>
                    <div>
                        <div>
                            <div className="mt-2.5">
                                <UserSearch />
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </>
    );
}
