import Head from 'next/head';
import { Response, User } from '@/utils/interface';
import UserCard from '@/components/UserCard';
import Alert from '@/components/Alert';
import Link from 'next/link';
import { getUsers } from '@/services/user';


export async function getServerSideProps(context: any) {
    const response = await getUsers(context.params.id);
    return { props: { data: response.data[0] || null } };
}

export default function UserPage({ data }: { data?: User }) {
    return (
        <>
            <Head>
                <title>{data?.name || 'Invalid user'} | User</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex justify-start flex-col items-center min-h-screen">
                <div className="my-36 md:w-96">
                    {data ? (
                        <UserCard name={data.name} email={data.email} />
                    ) : (
                        <Alert message="Url is invalid. Please try again later." />
                    )}
                </div>
                <div className="">
                    <Link
                        href="/"
                        className="ml-1 text-sm font-medium text-gray-700 hover:text-green-600 md:ml-2 dark:text-gray-400 dark:hover:text-white"
                    >
                        Back to home
                    </Link>
                </div>
            </main>
        </>
    );
}
